### ISSUE TITLE
Замечания по ILUT

### ISSUE THREAD

**Issue by dzheltkov** [MaximKiryakin/Household-Algorithm#2]
Пока что алгоритм не реализован, гд полученные факторы L и U?

**Comment by MaximKiryakin** [comment]
Я записываю из в исходную матрицу А, мне нужно отдельно их вывести в файлы?

**Comment by dzheltkov** [comment]
Их невозможно записать в исходную матрицу, в них может быть (и в подавляющем числе случаев будет) больше ненулевых элементов.

**Comment by MaximKiryakin** [comment]
Переписал алгоритм

**Comment by MaximKiryakin** [comment]
Дмитрий Александрович, я не понимаю, как мне сделать MPI для моего ILUT. В реализации я использую класс для разряженной матрицы, а если я хочу разослать задачи процессам и использовать MPI_Scatter, то там надо передавать указатель на начало буфер-матрицы, а у меня структура, из-за этого я не могу распараллелить(

**Comment by dzheltkov** [comment]
1. Вы пишите  `#pragma omp for`, но параллельная секция нигде не открыта. Поэтому на самом деле параллельность не используется.
2. Содержимое циклов не потокобезопасно, поэтому после добавления параллельной секции корректно работать не будет.
3. MPI версия не реализована.

**Comment by MaximKiryakin** [comment]
Исправил прагму
Добавил mpi

**Comment by dzheltkov** [comment]
1. В OpenMP всё ещё используются параллельные секции для непотокобезопасных функций. Зачесть не могу.
2. MPI версия достаточно печальная, зачесть могу, но на 3.

**Comment by MaximKiryakin** [comment]
1. Поправил, я так понимаю я не могу ставить параллельность на циклы с разряженными векторами, так как потом оно корректно не соберется со всех процессов.
2. 3 хватит

**Comment by dzheltkov** [comment]
В OpenMP всё ещё остались проблемы, все (вроде бы, может быть что-то и пропустил) применения некорректны и приведут к неопределённому поведению и / или ошибкам.

**Comment by MaximKiryakin** [comment]
в таком случае я не понимаю, почему

**Comment by MaximKiryakin** [comment]
я поправил

**Comment by dzheltkov** [comment]
Теперь фактически ничего не параллелится.
Это в целом потому, что реализовывать такой оператор и для последовательной версии не лучшая идея.
Но ладно, на 3 зачту.
